### ISSUE TITLE
support alternate location further for Handlers

### ISSUE THREAD

**Issue by wolftune** [alx741/yesod.vim#3] opened 2016-11-20 17:59 UTC
So, although we have src/Handler which works with the new update, all our route handlers aren't actually in separate files there. Instead, most of them are very simple, nearly just pass-through to Hamlet files, so we grouped them all into a single file src/Handler.hs

Perhaps vim-yesod could just use *tag* jumping (e.g. via hasktags) to know that a route in the routes file should jump to getRouteR ? Or you could just figure out a way to tell it that there's such a thing as that src/Handler.hs file *as well as* src/Handler/ separate files?

**Comment by alx741** [comment] 2016-11-21 02:33
Fair point. Will figure out a better way for this

**Comment by alx741** [comment] 2016-11-21 04:31
That should do it. Now the resource is looked up in all the handler files and adds the handler functions for every http method found for that resource in the location list, so doing `:lnext` and `:lprev` will take you to the next/prev http method of *that* resource.

If a resource handler is not found, it will prompt you in case you want to create it, but defaults to `No` in case you don't want to use *yesod-bin* for doing so and want to manually add it in a specific file.

**Comment by wolftune** [comment] 2016-11-21 04:49
Although I could quibble with the way our lead dev set this up, our project has `src/Handler/` with separate files *and* `src/Handler.hs`, so if I set `let g:yesod_handlers_path = "src/Handler"` in .vimrc, I think vim-yesod searches all files within the Handler/ directory but not the Handler.hs file that is *outside* of the Handler/ directory (as in, I'm getting not-found errors still for items in the src/Handler.hs file

**Comment by alx741** [comment] 2016-11-21 05:04
Such peculiar setup. Probably making the search recursive and setting the path to "src/", or a list of paths...  let me try that out

**Comment by alx741** [comment] 2016-11-21 18:24
Ok, now using `let g:yesod_handlers_path = "src/"` should do it (it will find your handlers recursively), check it out and please let me know.

**Comment by wolftune** [comment] 2016-11-21 18:29
It sorta works. I do `gh` and then I get this error:

```
"/src/Handler.hs" 138 lines --0%--
The resource for TestR does not exist. Create it? [y/N]
```

But if I say no, I am still redirected to Handler.hs, but just to the top of the file instead of to the getTestR function.

**Comment by alx741** [comment] 2016-11-21 18:48
There is another tweak, try it out

**Comment by wolftune** [comment] 2016-11-21 19:03
same error, but I should add a note:

We actually have the files all under website/ directory, but since routes is in website/config/routes, the website/ directory seems irrelevant. At any rate, I tries with website/src/ in .vimrc settings and that failed more while src/ alone worked in the partial way. I may have had website/src/ in the vimrc during earlier testing though… sorry for all the confusion

**Comment by alx741** [comment] 2016-11-21 19:15
Maybe I'm not reproducing your setup correctly, the plugin assumes that the directory that contains the handlers and `config` are at the same level, thus I'm assuming something like this:

yesod_project
|---- config
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|---- routes
|
|---- src
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|---- Hander.hs
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|---- Handler
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|---- HandlerFile1.hs
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|---- HandlerFile2.hs

Is that correct? I have that setup for testing it, and it works independently of the cwd, so I can open `routes` from everywhere and it will be able to find the handlers directory (if the `config` and `src` directories being at the same level assumption holds)

**Edit:**  I'm using `g:yesod_handlers_path = "src/"`

**Comment by wolftune** [comment] 2016-11-21 19:24
Well, the project is: https://github.com/snowdriftcoop/snowdrift so you can see the exact details there

It's
```
yesod_project
|----website
    |---- config
    |        |---- routes
    |
    |---- src
    |        |---- Hander.hs
    |        |---- Handler
    |                |---- HandlerFile1.hs
    |                |---- HandlerFile2.hs
```

**Comment by alx741** [comment] 2016-11-21 19:43
weird... I just cloned that repo, and it works flawlessly for me.

Using `:let g:yesod_handlers_path = "src/"`  I'm able to `gh` on every route in `routes` and It takes me to the handler.

I also tried opening the `routes` file while (pwd) in the repo root `snowdrift`, from `website`, from `config` and it works well each time.

Maybe double check the `:let g:yesod_handlers_path = "src/"`  it's being applied correctly, you can check just before trying `gh` with `:let g:yesod_handlers_path` and it should echo out `g:yesod_handlers_path src/`. Also make sure you're running the latest version of *vim-yesod* maybe you didn't get some of the very last commits I pushed (?)

**Comment by wolftune** [comment] 2016-11-21 20:09
`:let g:yesod_handlers_path` gave me `g:yesod_handlers_path src/`

I updated again, same error. very weird, glad it works for you…

**Comment by alx741** [comment] 2016-11-21 20:38
So the problem must be somewhere else. What does `$ vim --version` says?

**Comment by wolftune** [comment] 2016-11-21 20:39
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo                                                         
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     
```

**Comment by alx741** [comment] 2016-11-21 20:44
I'm using Vim 8.0.86, will try Vim 7.4.1689 and see if that replicates the issue

**Comment by alx741** [comment] 2016-11-21 21:30
Bad news: I tried Vim 7.4.1689 and it still works, then I tried (Vim 7.4.1689 as well) removing everything from my `.vimrc` except *vim-yesod* plugin loading and still works just fine...  

The only thing that I found mess things up if there is no present in `.vimrc` is `set nocompatible`, so in Vim running `:set compatible?` should echo out `nocompatible`. But that is the very first thing one configures in Vim so is unlikely your setup doesn't have it.

The error you're still getting is the exact same as this:

> It sorta works. I do gh and then I get this error:

> "/src/Handler.hs" 138 lines --0%--
> The resource for TestR does not exist. Create it? [y/N]

> But if I say no, I am still redirected to Handler.hs, but just to the top of the file instead of to the > getTestR function.

or has it changed in any way?  Because right after that I tried out and didn't work for me either, but the next commit fixed it for me, so maybe the error changed a bit (?)

**Comment by wolftune** [comment] 2016-11-22 00:08
I am getting the exact error I posted earlier. I didn't test with a clean vimrc though. The `nocompatible` thing is set correctly.

**Comment by alx741** [comment] 2016-11-22 04:40
Would you mind trying with my `.vimrc`?  Maybe we can get some information out of that.

https://github.com/alx741/dotfiles/blob/master/vim/.vimrc

**Comment by wolftune** [comment] 2016-11-22 04:54
I'm just getting `--SELECT--` showing and nothing else when I do `gh`, but I didn't go ahead and run everything and install all the plugins etc. it's quite a massive vimrc you have there. I assume that since I already have vim-yesod installed, it will work in both cases, although that may be wrong.

Incidentally, I tried back on my setup to go ahead and accept making a new handler to see what would happen, but I don't have yesod-bin installed. Is there any chance that's needed for even the jumping?

**Comment by alx741** [comment] 2016-11-22 14:30
Yes, I guess that wouldn't be necessary, **however**, if you're getting `--SELECT--` it means the plugins is either not installed or not being loaded, because the default `gh` behavior is to start *select mode*, which is what you're getting there.



> Incidentally, I tried back on my setup to go ahead and accept making a new handler to see what would > happen, but I don't have yesod-bin installed. Is there any chance that's needed for even the jumping?

I did notice that as well, it is because of the particular setup of your project: It's not using the standard Yesod tree and so yesod-bin gets confused, there is no easy fix for this though, it depends on how yesod-bin behaves and there is no way to configure it to use the standard files in different locations.

But the jumping functionality is completely independent and does not use yesod-bin so the problem must be somewhere else. Bummer

**Comment by alx741** [comment] 2016-11-22 14:44
Ok, I have an idea: while editing `config/routes` on the **snowdrift** project, at least one of these three should take you to the `PaymentInfoR` handler:

```vim
:exe "lvimgrep /PaymentInfoR *::/ " . expand("%:p:h") . "/../src/**/*"
:exe "lvimgrep /PaymentInfoR ::/ " . expand("%:p:h") . "/../src/**/*"
:exe "lvimgrep /PaymentInfoR/ " . expand("%:p:h") . "/../src/**/*"
```

**Comment by wolftune** [comment] 2016-11-22 17:59
I get for the first two:
```
"website/src/Handler/PaymentInfo.hs" 99L, 3671C
E926: Current location list was changed
```
and the last:
```
"website/src/Handler/PaymentInfo.hs" 99 lines --1%--
E926: Current location list was changed
```
so, no those didn't work :(

**Comment by alx741** [comment] 2016-11-22 18:42
Ok, that is very informative because it's just a straightforward *lvimgrep* call that has no reason to fail whatsoever.

I've researching it and turns out it's because of a pretty nasty bug in Vim itself introduced in [7.4.1640](http://ftp.vim.org/pub/vim/patches/7.4/7.4.1640). Although the bug is know to occur for the location list, I fond no information about the quickfix list so lets try the same as before but with `vimgrep` instead of `lvimgrep`: 

```vim
:exe "vimgrep /PaymentInfoR *::/ " . expand("%:p:h") . "/../src/**/*"
:exe "vimgrep /PaymentInfoR ::/ " . expand("%:p:h") . "/../src/**/*"
:exe "vimgrep /PaymentInfoR/ " . expand("%:p:h") . "/../src/**/*"
```

**Comment by wolftune** [comment] 2016-11-22 18:47
The first two worked! The last one brought me to the `getPaymentInfoR` on line 3, the module listing instead of the actual function.

**Comment by alx741** [comment] 2016-11-22 19:13
Awesome! that's exactly what it should do. So there are workarounds that don't completely solve the issue here and won't fit in this use case anyways so if possible you should update Vim to a newer version. But before taking a decision about how to address this for version of Vim affected by the bug, lets try a modification of the failing command:

```vim
:exe "lvimgrep /PaymentInfoR *::/j " . expand("%:p:h") . "/../src/**/*"
```
Notice the `j` around the middle. This shouldn't do too much (no jumping), and then:

```vim
:ll
```

That should (hopefully) take you to the `PaymentInfoR` Handler without errors

**Comment by wolftune** [comment] 2016-11-22 19:40
bad news, that doesn't solve it. Maybe there's no solution with this buggy version of vim (which is unfortunately the Ubuntu standard version)

**Comment by alx741** [comment] 2016-11-22 19:55
Well I guess I'll add some conditional to use the quickfix list for vim <= 7.4 and the location list otherwise... not the cleanest and nicer solution but it gets the job pretty much done ¯\\\_(ツ)\_/¯

**Closed as completed** 2016-11-23 04:35 UTC
Labels: bug, enhancement, known bugs

**Comment by alx741** [comment] 2016-11-23 04:37
Ok, lets hope now it's solved.

As documented in the `README` file, for your version of Vim, you'll use `:cnext` and `:cprev` in order to jump between the available http methods for that handler. As soon as you hit `gh` it should take you to the first occurrence of course.

**Comment by wolftune** [comment] 2016-11-23 04:40
It's solved!! Works perfectly, yay!

**Comment by alx741** [comment] 2016-11-23 04:42
Awesome!! 😃
